export const PROMPT_REGISTRY = [
  {
    name: "support-classify",
    version: "v1",
    taskType: "classification",
    outputMode: "json",
    validationSchema: "ClassifyOutputSchema",
    contextPolicy: "message + userRole + currentPage",
    riskLevel: "low",
    owner: "backend",
    requiredTests: ["ambiguous_message", "erp_access_problem"],
  },
  {
    name: "ticket-data-query",
    version: "v1",
    taskType: "data_query",
    outputMode: "json",
    validationSchema: "QuerySpecSchema",
    contextPolicy: "schema only, no raw table data",
    riskLevel: "medium",
    owner: "backend",
    requiredTests: [
      "list_query",
      "count_query",
      "unsupported_write_action",
      "user_scope_applied",
    ],
  },
  {
    name: "task-automation",
    version: "v1",
    taskType: "automation",
    outputMode: "json",
    validationSchema: "AutomationProposalSchema",
    contextPolicy: "conversationState + allowedActions",
    riskLevel: "high",
    owner: "backend",
    requiredTests: [
      "create_draft_requires_confirmation",
      "forbidden_close_ticket",
      "missing_fields",
    ],
  },
  {
    name: "guided-support",
    version: "v1",
    taskType: "guided_interaction",
    outputMode: "json",
    validationSchema: "GuidedSupportOutputSchema",
    contextPolicy: "sessionState + current user message",
    riskLevel: "medium",
    owner: "backend",
    requiredTests: [
      "new_erp_issue",
      "ambiguous_goal",
      "ticket_status_goal",
    ],
  },
  {
    name: "styled-response",
    version: "v1",
    taskType: "response_generation",
    outputMode: "text",
    validationSchema: "GeneratedResponseValidator",
    contextPolicy: "decision + styleProfile",
    riskLevel: "medium",
    owner: "backend",
    requiredTests: [
      "end_user_short_response",
      "support_agent_bullets",
      "safe_refusal",
    ],
  },
];
